# Using Python for Statistics
#### Chris Tibbitts

Table of Contents
1. Numpy Warmup
2. Data Exploration/Analysis

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

/var/folders/3r/y18r0bfn0r7dzjscjkt3j9hm0000gn/T/ipykernel_14315/4114694703.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

## Numpy Warmup

## Data Exploration/Analysis

In [3]:
data = pd.read_csv("2021-PM2.5.csv")
data

,Date,BV-MC,CV-MC,ED-MC,EN-MC,H3-MC,H3-MC-CO,HA-MC,HC-MC,HV-MC,...,NR-MC,RP-MC,RS-MC,RS-MC-CO,SF-MC,SM-MC-CO,SM-MC-CO2,UT-MC,UT-MC-CO,V4-MC
0,2021-01-01 00:00:00,40.0,26.5,30.1,5.4,7.8,6.8,24.6,2.1,42.6,...,30.2,27.6,12.4,12.0,20.9,41.2,46.5,21.7,NaN,14.6
1,2021-01-01 01:00:00,41.2,25.5,31.2,4.9,5.4,3.8,30.4,2.1,33.8,...,36.8,26.4,13.8,13.4,20.5,42.4,49.3,13.3,NaN,15.5
2,2021-01-01 02:00:00,27.0,26.0,27.3,5.5,4.4,3.5,30.5,2.2,41.3,...,39.8,26.4,17.6,15.6,23.0,45.4,52.5,19.4,NaN,17.2
3,2021-01-01 03:00:00,27.1,25.5,16.8,6.7,3.3,2.6,31.1,2.9,37.6,...,33.9,36.1,19.5,16.5,25.6,38.1,42.8,27.7,NaN,14.9
4,2021-01-01 04:00:00,30.2,26.0,8.6,6.3,3.1,2.6,34.5,3.7,24.8,...,34.2,33.6,18.6,15.8,24.0,40.4,45.5,27.9,NaN,13.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2021-12-31 19:00:00,6.0,5.5,1.2,1.8,1.4,0.2,3.5,1.9,0.8,...,4.0,1.7,11.1,8.2,0.4,1.1,1.5,1.0,NaN,1.5
8756,2021-12-31 20:00:00,4.5,2.5,0.5,1.6,1.7,0.4,5.5,1.6,1.0,...,5.1,0.7,0.6,0.7,1.0,1.8,2.3,0.8,NaN,4.3
8757,2021-12-31 21:00:00,5.7,1.9,1.0,1.4,2.2,0.6,8.7,0.6,2.1,...,1.8,1.8,1.9,1.8,1.0,5.9,7.0,1.8,NaN,13.7
8758,2021-12-31 22:00:00,5.4,6.7,0.7,1.4,2.8,0.8,9.2,0.8,3.7,...,4.9,2.7,1.8,1.9,1.3,8.2,9.5,1.9,NaN,1.6
8759,2021-12-31 23:00:00,3.9,3.1,2.6,0.8,1.8,0.3,6.9,0.7,4.3,...,6.3,4.6,3.1,3.0,0.7,3.2,3.8,1.9,NaN,1.2

In [4]:
data.describe()

,BV-MC,CV-MC,ED-MC,EN-MC,H3-MC,H3-MC-CO,HA-MC,HC-MC,HV-MC,HW-MC,...,NR-MC,RP-MC,RS-MC,RS-MC-CO,SF-MC,SM-MC-CO,SM-MC-CO2,UT-MC,UT-MC-CO,V4-MC
count,8386.000000,8623.000000,8661.000000,8742.000000,8278.000000,8638.000000,8743.000000,8234.000000,8261.000000,8691.000000,...,8755.000000,8699.00000,8502.000000,8329.000000,8719.000000,8520.000000,8575.000000,8743.000000,1218.000000,8730.000000
mean,9.287264,9.450609,7.961552,6.590517,7.640058,6.418847,8.547627,6.118812,8.200097,9.339432,...,11.158172,9.55557,7.413232,7.047185,7.463585,8.941526,9.217061,9.412764,5.759442,7.380195
std,9.804585,9.483888,10.644967,7.832313,10.318708,7.657604,9.146856,6.672681,8.680877,9.778577,...,10.280355,9.97351,8.264591,8.142102,8.237558,9.636080,9.909044,9.430916,3.372304,8.456893
min,-0.300000,-0.100000,-0.300000,0.000000,-1.500000,-0.100000,-5.600000,-0.100000,0.000000,0.400000,...,0.200000,-0.20000,-0.400000,0.000000,0.000000,0.100000,0.100000,0.300000,0.600000,0.100000
25%,3.400000,3.700000,2.300000,2.800000,2.400000,2.100000,3.000000,2.800000,2.800000,3.650000,...,4.800000,3.50000,2.900000,2.400000,2.900000,3.200000,3.200000,3.600000,3.500000,2.900000
50%,6.300000,6.800000,4.900000,4.700000,4.900000,4.200000,6.000000,4.700000,5.500000,6.400000,...,8.300000,6.50000,4.700000,4.400000,5.200000,5.700000,5.800000,6.600000,5.100000,4.600000
75%,11.100000,11.700000,9.600000,7.700000,8.600000,7.900000,10.500000,7.500000,10.200000,10.950000,...,14.200000,11.70000,8.700000,8.500000,9.000000,10.800000,11.050000,11.700000,7.200000,8.300000
max,105.900000,114.200000,286.100000,106.700000,150.800000,103.900000,91.500000,97.500000,101.800000,110.000000,...,107.300000,105.40000,97.900000,96.400000,122.700000,80.000000,80.300000,109.900000,44.500000,90.200000